# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parse-RecDescent-Topiary
version:      0.04
version_from: lib/Parse/RecDescent/Topiary.pm
installdirs:  site
requires:
    Module::Optional:              0
    Parse::RecDescent:             0
    Scalar::Util:                  0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
