--- #YAML:1.0
name:                Parse-RecDescent-Topiary
version:             0.05
abstract:            tree surgery for Parse::RecDescent autotrees
license:             perl
author:              
    - Ivor Williams (ivorw@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Module::Optional:              0
    Parse::RecDescent:             0
    Scalar::Util:                  0
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
